name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-version: ['v0.7.0', 'v0.8.0', 'v0.9.0', 'stable']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Neovim
        uses: rhymond/setup-neovim@v1
        with:
          neovim-version: ${{ matrix.nvim-version }}
      
      - name: Install dependencies
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/deps/start
          git clone https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/deps/start/plenary.nvim
      
      - name: Run basic syntax check
        run: |
          nvim --headless -c "lua loadfile('lua/buildkite/init.lua')()" -c "qa!"
      
      - name: Test module loading
        run: |
          nvim --headless -c "lua require('buildkite.config')" -c "qa!"
          nvim --headless -c "lua require('buildkite.api')" -c "qa!"
          nvim --headless -c "lua require('buildkite.commands')" -c "qa!"
          nvim --headless -c "lua require('buildkite.git')" -c "qa!"
          nvim --headless -c "lua require('buildkite.health')" -c "qa!"
      
      - name: Test health check
        run: |
          nvim --headless -c "lua require('buildkite.health').check()" -c "qa!"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      
      - name: Run luacheck
        run: |
          luacheck lua/ --globals vim